# Generated by Django 3.2.13 on 2022-06-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_couont', models.IntegerField(default=0, verbose_name='访问次数')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('file_upload_time', models.DateTimeField(default=datetime.datetime(2022, 6, 6, 23, 5, 48, 475593), verbose_name='上传时间')),
                ('file_save_path', models.CharField(max_length=64, verbose_name='文件存储路径')),
                ('file_name', models.CharField(max_length=32, verbose_name='文件名')),
                ('file_size', models.CharField(max_length=8, verbose_name='文件大小')),
                ('customer_upload_ip', models.CharField(max_length=16, verbose_name='客户端上传的IP地址')),
            ],
        ),
    ]
