# Generated by Django 3.2.13 on 2022-06-07 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fileShareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 18, 28, 51, 548452, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
